const screen=document.getElementById('screen');let rockLevel=1,whyFound=0;
const rock=()=>`<div class="rock l${rockLevel}">🪨</div>`;
const duo=()=>`<div class="duo"><div class="otter" title="Océane">🦦</div><div class="otter" title="Olivier">🦦</div></div>`;
const btn=(label,fn,alt=false)=>`<button class="${alt?'alt':''}" onclick="${fn}()">${label}</button>`;
function show(html){screen.innerHTML=`<div class="card fadein">${html}</div>`;window.scrollTo({top:0,behavior:'smooth'})}
function start(){rockLevel=1;show(`<div class="scene-art">${duo()}</div><div class="pixel">PROJECT : LOULOUTRE</div><h1>Une petite aventure<br>pour mon cachaphoque.</h1><p>Une quête créée spécialement pour toi.</p>${btn('▶ COMMENCER','intro')}`)}
function intro(){show(`<div class="scene-art">${duo()}</div><h2>Bienvenue, Olivier.</h2><p>Une quête très sérieuse t'attend.</p><div class="questbox">WARNING<br><br>Ce jeu contient :<br>🦦 des loutres<br>🎮 des jeux vidéo<br>💙 beaucoup trop d'amour<br>🍹 une pina colada potentiellement dangereuse<br>💨 des flatulences<br>🩲 des vérifications vestimentaires<br>🪨 un caillou</div>${btn('ACCEPTER LES RISQUES','meeting')}`)}
function meeting(){show(`<div class="scene-art">${duo()}</div><div class="pixel">SCÈNE 1</div><h2>Et tout a commencé comme ça.</h2><p><b>Début février.</b> Deux personnes se rencontrent sur Boo.</p><p>Premier rendez-vous : un restaurant.</p><p>Tout semblait bien parti… jusqu'à ce que Olivier arrive avec <b>15 minutes de retard.</b></p><p>Océane : ☁️</p>${btn('SUIVANT','meeting2')}`)}
function meeting2(){rockLevel=2;show(`<div class="scene-art">${duo()}</div><p>La quête semblait plutôt mal engagée.</p><p>Mais finalement, vous êtes allés chez lui.</p><p class="quote"><span class="nowrap-quote">« Et depuis, on ne s'est plus lâchés. »</span></p>${rock()}<p class="muted">Le caillou gagne une petite lueur bleue.</p>${btn('CONTINUER','why')}`)}
function why(){whyFound=0;show(`<div class="scene-art"><div class="otter">🦦</div></div><div class="pixel">SCÈNE 2</div><h2>À ton avis, pourquoi je t’aime ?</h2><p>Clique sur la/les bonne(s) réponse(s).</p><div class="grid" id="whyGrid"><button onclick="whyTap(this,'🧠 Ton intelligence.')">🧠 Intelligence</button><button onclick="whyTap(this,'👁️ Tes beaux yeux bleus.')">👁️ Yeux bleus</button><button onclick="whyTap(this,'🌙 Ton calme.')">🌙 Calme</button><button onclick="whyTap(this,'✦ Ton côté complètement silly.')">✦ Silly</button></div><p id="whyOut" class="quote"></p>`)}
function whyTap(el,text){if(el.disabled)return;el.disabled=true;whyFound++;document.getElementById('whyOut').insertAdjacentHTML('beforeend',`<span class="fadein">${text}<br></span>`);if(whyFound===4)setTimeout(whyFinal,500)}
function whyFinal(){rockLevel=3;show(`<div class="scene-art">${duo()}</div><h2>Et puis il y avait quelque chose de plus difficile à expliquer.</h2><p class="quote">« Tu es la personne la plus inspirante que j'ai pu rencontrer. »</p>${rock()}${btn('SUIVANT','archives')}`)}
function archives(){show(`<div class="pixel">SCÈNE 3</div><h2>⚠ Archives compromettantes</h2><p class="muted">Certaines informations auraient dû rester secrètes.</p><div class="grid"><div class="tile"><h3>💨 GUESS MY FART</h3><p>Une activité parfaitement normale dans un couple.</p></div><div class="tile"><h3>🍹 LA PINA COLADA</h3><p>Premier cocktail de Olivier.<br>Goût : ⭐⭐⭐⭐⭐<br>Survie d’Océane : ☠️<br>Effets secondaires : plusieurs jours.</p></div><div class="tile"><h3>🩲 L'INCIDENT</h3><p>Première rencontre avec ta mère : équipement incomplet.<br><b>PASSIVE SKILL UNLOCKED: UNDERWEAR CHECK.</b></p></div><div class="tile"><h3>🎆 LE FEU D'ARTIFICE</h3><p>14 juillet.<br>Objectif : voir le feu d'artifice.<br><b>Feux observés : 0.</b><br>QUEST FAILED.</p></div></div>${btn('CONTINUER','thanks')}`)}
function thanks(){rockLevel=4;show(`<div class="scene-art">${duo()}</div><div class="pixel">SCÈNE 4</div><h2>Merci.</h2><p class="letter">Merci d'être là quand ça ne va pas.<br><br>Merci de toujours essayer, même quand ça ne marche pas.<br><br>Merci de me faire rire, mon louloutre.<br><br>Merci de toujours essayer de me faire plaisir.<br><br>Merci de t'adapter pour moi.<br><br>Merci de m'encourager dans ce que je fais.<br><br>Merci de m'intégrer dans ta vie et dans ton entourage.<br><br>Merci de m'offrir des cadeaux toujours adaptés à ce que j'aime.<br><br>Merci d'avoir confiance en moi.<br><br><b>Merci de m'aimer.</b></p>${btn('IL Y A AUSSI UNE CHOSE…','storm')}`)}
function storm(){show(`<div class="scene-art">${duo()}</div><p class="muted">Une nuit. Un orage.</p><p class="quote">« Quand j'ai peur, tu me prends dans tes bras et tu me rassures. »</p><p class="quote">« Ça va aller. »</p><p>Je ne sais pas si tu réalises à quel point ces mots peuvent compter pour moi.</p>${rock()}${btn('CONTINUER','future')}`)}
function future(){rockLevel=5;show(`<div class="scene-art">${duo()}</div><div class="pixel">SCÈNE 5 — NEW QUEST</div><h2>Et maintenant ?</h2><p>La suite de l'histoire n'est pas encore écrite.</p><div class="future"><div>🇯🇵<br>Découvrir le Japon</div><div>🚢<br>Faire des croisières</div><div>🎮<br>Jouer côte à côte</div><div>🐈<br>Être entourés de chats</div><div>👶👶<br>Au moins deux bébés</div><div>♾️<br>Vieillir ensemble</div></div><p class="quote">« Quand je pense à nous, je pense à notre avenir et à combien il me plairait de passer le mien à tes côtés. »</p>${btn('DERNIÈRE QUÊTE','declaration')}`)}
function declaration(){rockLevel=6;show(`<div class="scene-art">${duo()}</div><h2>La vraie quête.</h2><p class="letter">Je suis tombée amoureuse de toi parce que tu es la personne la plus inspirante que j'ai pu rencontrer.</p><p class="letter">Une chose que tu fais et que je ne dis peut-être pas assez, c'est de continuer à croire et à avancer avec toujours autant d'amour dans tes yeux.</p><p class="letter">Avec toi, je me sens en sécurité.</p><p class="letter"><b>Peu importe combien ça peut être difficile parfois, notre histoire vaut le coup.</b></p><p class="letter">Et si je pouvais te dire une dernière chose, ce serait que je t'aime et t'aimerais toujours.</p>${rock()}${btn('UN DERNIER CADEAU…','reward')}`)}
function reward(){show(`<div class="scene-art">${duo()}</div><div class="pixel">REWARD UNLOCKED</div><h2>🍽️ Une soirée à deux</h2><p><b>Destination :</b> ???<br><b>Participants :</b> 2 loutres<br><b>Date :</b> à choisir ensemble</p>${btn("OUVRIR L'INVITATION",'restaurant')}`)}
function restaurant(){show(`<div class="scene-art">${duo()}</div><div class="pixel">FINAL REWARD</div><h1>KERLITA 💙</h1><p class="quote">Je t'invite à dîner dans notre restaurant préféré.</p><p>Parce que je t'aime.<br>Parce que je voulais te remercier.<br>Et parce que j'ai envie de continuer notre aventure avec toi.</p>${btn('♥ ACCEPTER LA QUÊTE','end',true)}${rock()}`)}
function end(){show(`<div class="scene-art">${duo()}</div><div class="pixel">QUEST ACCEPTED</div><h1>💙</h1><p class="quote">« La prochaine aventure, on la fera ensemble. »</p>${rock()}<p class="muted">P.S. : je penserais à mettre une culotte, promis !</p>${btn('↻ REJOUER','start')}`)}
start();
